name: Run RuboCop and Rspec

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint and Syntax Check
    runs-on: ubuntu-latest

    # Define the Docker container to use for the job
    container:
      image: docker://ruby:2.7.6  # Use the specific version of Ruby image from Docker Hub

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: bundle exec rake rubocop

    - name: Run Rspec
      run: bundle exec rake rspec
